[package]
edition = "2021"
name = "rp2040-timer-int"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]

cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = "0.2.7"
panic-halt = "0.2.0"
rp-pico = "0.8.0"
rp2040-hal = "0.9.2"
fugit = "0.3.7"
critical-section = "1.1.2"

